<a href="https://colab.research.google.com/github/ssjeson412/BDS-M1/blob/M1/recommender_systems/24th%20Sept%20M1_Recap_Recommender_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
# Importing necessary libraries.
import pandas as pd
import scipy.sparse as ss
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_distances

In [85]:
df_trips = pd.read_csv('https://sds-aau.github.io/SDS-master/M1/data/trips.csv')

In [86]:
df_trips.head()

,Unnamed: 0,username,country,country_code,country_slug,date_end,date_start,latitude,longitude,place,place_slug
0,0,@lewellenmichael,Mexico,MX,mexico,2018-06-15,2018-06-04,21,-101,Guanajuato,mexico
1,1,@lewellenmichael,Mexico,MX,mexico,2018-06-03,2018-05-31,19,-99,Mexico City,mexico-city-mexico
2,2,@lewellenmichael,Mexico,MX,mexico,2017-11-05,2017-11-01,21,-86,Cancun,cancun-mexico
3,3,@lewellenmichael,Jordan,JO,jordan,2017-08-07,2017-07-24,31,35,Amman,amman-jordan
4,4,@waylandchin,China,CN,china,2017-03-18,2017-02-17,40,122,Yingkou,china


In [87]:
# Creating user-place matrix using df_trips
trips_matrix = pd.crosstab(df_trips['username'], df_trips['place_slug'])
display(trips_matrix.head())

place_slug,11000,180-40,45230,630-72,671-03,847-00,a-coruna-spain,aachen-germany,aalborg-denmark,aalesund-norway,...,york-united-kingdom,zadar-croatia,zagreb-croatia,zambia,zhangjiakou-china,zhengzhou-china,zhuhai-china,zimbabwe,zurich-switzerland,zwolle-netherlands
username,,,,,,,,,,,,,,,,,,,,,
@01aniqe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@0chucha0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@10kjuan,0,0,0,0,0,0,0,0,0,0,...,0,0,3,0,0,0,0,0,0,0
@123456,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@1ikigai,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [88]:
# Calculate the pairwise cosine distance matrix between users
user_distances = cosine_distances(matrix_user_place)

# Convert distances to similarity: similarity = 1 - distance
user_similarity = 1 - user_distances
print("User Similarity Matrix Shape:", user_similarity.shape)

# Display a slice of the similarity matrix
user_similarity

User Similarity Matrix Shape: (2871, 2871)


array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.36335108,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.36335108, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [89]:
###################################################
#   Step 1: Label Encoding and Matrix Creation    #
###################################################
# Initialize label encoders
le_user = LabelEncoder()
le_place = LabelEncoder()
# Label encode usernames and place slugs
df_trips['username_id'] = le_user.fit_transform(df_trips['username'])
df_trips['place_slug_id'] = le_place.fit_transform(df_trips['place_slug'])

# Create a sparse matrix

# Create the sparse matrix using the 'username_id' and 'place_slug_id' columns as indices
matrix = pd.crosstab(df_trips['username_id'], df_trips['place_slug_id'])

###################################################
#    Step 2: Perform Dimensionality Reduction     #
###################################################
svd = TruncatedSVD(n_components=5, n_iter=7, random_state=42)
#These latent features could potentially capture characteristics like how popular a place is
matrix_places = svd.fit_transform(matrix.T)

###################################################
#    Step 3: Calculate The Similarity Matrix      #
###################################################
cosine_distance_matrix_places = cosine_distances(matrix_places)

In [90]:
cosine_distance_matrix_places.shape

(961, 961)

In [91]:
cosine_distance_matrix_places

array([[0.        , 0.93737257, 0.94042055, ..., 0.55101577, 0.94479183,
        0.66700793],
       [0.93737257, 0.        , 0.2219977 , ..., 0.55865144, 1.01683665,
        0.55894041],
       [0.94042055, 0.2219977 , 0.        , ..., 0.42547908, 0.90915149,
        0.12785817],
       ...,
       [0.55101577, 0.55865144, 0.42547908, ..., 0.        , 0.35913659,
        0.36126287],
       [0.94479183, 1.01683665, 0.90915149, ..., 0.35913659, 0.        ,
        0.89817704],
       [0.66700793, 0.55894041, 0.12785817, ..., 0.36126287, 0.89817704,
        0.        ]])

In [92]:
df_trips = pd.read_csv('https://sds-aau.github.io/SDS-master/M1/data/trips.csv')
df_trips.shape # (46510, 14)

(46510, 11)

In [93]:
le_users, le_items = LabelEncoder(), LabelEncoder()
df_trips['username_id'] = le_users.fit_transform(df_trips['username'])
df_trips['place_slug_id'] = le_items.fit_transform(df_trips['place_slug'])
matrix_user_place = pd.crosstab(df_trips['username_id'], df_trips['place_slug_id'])
matrix_user_place.shape # (2871, 961)


(2871, 961)

In [94]:
svd = TruncatedSVD(n_components=5, n_iter=7, random_state=42)
matrix_user_place_dr = svd.fit_transform(matrix_user_place)
matrix_user_place_dr.shape # (2871, 5)

(2871, 5)

In [95]:
D = cosine_distances(matrix_user_place_dr) # (2871, 2871)
i = le_users.transform(['@cw'])[0] # 555
np.argsort(D[i, :])[:5] # [555, 2644, 153, 1371, 702]
le_users.inverse_transform(np.argsort(D[i, :])[:5])

array(['@cw', '@travpreneur', '@andrea', '@katehuentelman', '@dpashley'],
      dtype=object)

In [96]:
mine = df_trips[df_trips.username_id == 555]['place_slug_id'].unique()
theirs = df_trips[df_trips.username_id == 2644]['place_slug_id'].unique()
le_items.inverse_transform(theirs[~np.isin(theirs, mine)])[:10]

array(['pune-india', 'manchester-united-kingdom',
       'san-diego-ca-united-states', 'san-jose-ca-united-states',
       'amsterdam-netherlands', 'birmingham-united-kingdom',
       'mumbai-india', 'victoria-seychelles', 'johannesburg-south-africa',
       'delhi-india'], dtype=object)

In [97]:
matrix_place_user = matrix_user_place.T # (961, 2871)
matrix_place_user_dr = svd.fit_transform(matrix_place_user) # (961, 5)
Dp = cosine_distances(matrix_place_user_dr) # (961, 961)

In [98]:
j = le_items.transform(['paris-france'])[0] # 626
np.argsort(Dp[j, :])[:5] # [626, 735, 12, 172, 856]
le_items.inverse_transform(np.argsort(Dp[j, :])[:5])

array(['paris-france', 'france', 'grenoble-france', 'gothenburg-sweden',
       'malta'], dtype=object)

In [99]:
# Constructing the user-to-place matrix
user_place_matrix = pd.crosstab(df_trips['username'], df_trips['place_slug'])
print("Matrix Shape:", user_place_matrix.shape)
user_place_matrix.head()

Matrix Shape: (2869, 960)


place_slug,11000,180-40,45230,630-72,671-03,847-00,a-coruna-spain,aachen-germany,aalborg-denmark,aalesund-norway,...,york-united-kingdom,zadar-croatia,zagreb-croatia,zambia,zhangjiakou-china,zhengzhou-china,zhuhai-china,zimbabwe,zurich-switzerland,zwolle-netherlands
username,,,,,,,,,,,,,,,,,,,,,
@01aniqe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@0chucha0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@10kjuan,0,0,0,0,0,0,0,0,0,0,...,0,0,3,0,0,0,0,0,0,0
@123456,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@1ikigai,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [100]:
# Importing necessary libraries.
import pandas as pd
import scipy.sparse as ss
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_distances

In [101]:
df_trips = pd.read_csv('https://sds-aau.github.io/SDS-master/M1/data/trips.csv')

In [102]:
df_trips.shape

(46510, 11)

In [103]:
df_trips.username.value_counts()

,count
username,
@scottbrills,858
@adamnowek,678
@tkrunning,335
@replay,299
@photostraveller,255
...,...
@kschroeder,1
@becky,1
@stollz,1


In [104]:
df_trips.country.value_counts()

,count
country,
United States,7573
Thailand,3372
United Kingdom,2230
Germany,2019
Spain,1975
...,...
New Caledonia,1
Iguazu Falls,1
Åland Islands,1


In [105]:
df_trips.columns

Index(['Unnamed: 0', 'username', 'country', 'country_code', 'country_slug',
       'date_end', 'date_start', 'latitude', 'longitude', 'place',
       'place_slug'],
      dtype='object')

In [106]:
df_trips[['username', 'country']]

,username,country
0,@lewellenmichael,Mexico
1,@lewellenmichael,Mexico
2,@lewellenmichael,Mexico
3,@lewellenmichael,Jordan
4,@waylandchin,China
...,...,...
46505,@antonioc,Cuba
46506,@antonioc,Costa Rica
46507,@antonioc,United States
46508,@jrearden,United States


In [107]:
pd.crosstab(df_trips['username'], df_trips['country'])

country,11000,180 40,45230,630 72,671 03,847 00,AB30,AD100,Abkhazia,Afghanistan,...,Uruguay,Uzbekistan,Vatican City,Venezuela,Vietnam,Western Sahara,Yemen,Zambia,Zimbabwe,Åland Islands
username,,,,,,,,,,,,,,,,,,,,,
@01aniqe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@0chucha0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@10kjuan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@123456,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@1ikigai,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
@zsoltee,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@zuzapogopl,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
@zwasham,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [108]:
pd.crosstab(df_trips['username'], df_trips['country']).shape

(2869, 249)

In [109]:
matrix = pd.crosstab(df_trips['username'], df_trips['country'])

In [110]:
cosine_distances(matrix)

array([[0.       , 1.       , 1.       , ..., 1.       , 1.       ,
        1.       ],
       [1.       , 0.       , 1.       , ..., 1.       , 1.       ,
        1.       ],
       [1.       , 1.       , 0.       , ..., 1.       , 0.5150344,
        1.       ],
       ...,
       [1.       , 1.       , 1.       , ..., 0.       , 1.       ,
        1.       ],
       [1.       , 1.       , 0.5150344, ..., 1.       , 0.       ,
        1.       ],
       [1.       , 1.       , 1.       , ..., 1.       , 1.       ,
        0.       ]])

In [111]:
np.dot(matrix, matrix.T)

array([[  1,   0,   0, ...,   0,   0,   0],
       [  0,   2,   0, ...,   0,   0,   0],
       [  0,   0, 861, ...,   0,  45,   0],
       ...,
       [  0,   0,   0, ...,   2,   0,   0],
       [  0,   0,  45, ...,   0,  10,   0],
       [  0,   0,   0, ...,   0,   0,   5]])

In [112]:
np.dot(matrix, matrix.T).shape

(2869, 2869)

In [113]:
pd.crosstab(df_trips['country'], df_trips['username'])

username,@01aniqe,@0chucha0,@10kjuan,@123456,@1ikigai,@5ee8688fa7e64c5,@7farah7,@9102180,@_yuks,@a,...,@zoxel,@zpeirce,@zrephel,@zrueda,@zsofiaszarka,@zsoltee,@zuzapogopl,@zwasham,@zywy,@zzap
country,,,,,,,,,,,,,,,,,,,,,
11000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
180 40,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45230,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
630 72,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
671 03,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Western Sahara,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Yemen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Zambia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [114]:
pd.crosstab(df_trips['country'], df_trips['username']).shape

(249, 2869)

In [115]:
matrix_user = pd.crosstab(df_trips['country'], df_trips['username'])

In [116]:
matrix_item = pd.crosstab(df_trips.country, df_trips.username)

In [117]:
np.dot(matrix, matrix.T)

array([[  1,   0,   0, ...,   0,   0,   0],
       [  0,   2,   0, ...,   0,   0,   0],
       [  0,   0, 861, ...,   0,  45,   0],
       ...,
       [  0,   0,   0, ...,   2,   0,   0],
       [  0,   0,  45, ...,   0,  10,   0],
       [  0,   0,   0, ...,   0,   0,   5]])

In [118]:
np.dot(matrix, matrix.T).shape

(2869, 2869)

In [120]:
le_users.transform(['@scottbrills'])

array([2321])

In [122]:
le_country = LabelEncoder()
le_country.fit(df_trips['country'])
le_country.transform(['Denmark'])

array([70])

In [126]:
df_trips['username_id'] = le_users.fit_transform(df_trips['username'])
df_trips['country_id'] = le_country.fit_transform(df_trips['country'])

In [123]:
Matrix_item = pd.crosstab(df_trips.country, df_trips.username)

In [124]:
matrix_item_sin = cosine_distances(Matrix_item)

In [127]:
le_country.transform(['Denmark'])

array([70])

In [128]:
matrix_item_sin[70]

array([1.        , 0.97688749, 0.97688749, 0.97688749, 0.97688749,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.97301766, 1.        , 1.        , 0.95822663, 0.97724038,
       0.97688749, 0.94032376, 0.98966377, 0.95925547, 0.98665599,
       0.97226499, 0.98844375, 0.92579871, 0.88237889, 0.97212527,
       0.97688749, 0.99229583, 0.65331238, 0.98717949, 0.99314262,
       0.81629269, 0.99530387, 0.95377498, 0.97076473, 1.        ,
       0.95237879, 0.98980834, 1.        , 0.90611655, 0.83656989,
       0.98486931, 0.95838163, 1.        , 0.93462795, 0.91991089,
       1.        , 0.96721263, 1.        , 0.8549124 , 0.99570811,
       0.96899132, 1.        , 1.        , 1.        , 0.96524903,
       0.91290744, 0.97688749, 0.97932754, 0.9234831 , 1.        ,
       0.94249871, 1.        , 0.83659303, 0.78652044, 0.96419426,
       0.97351806, 0.97885225, 0.88077051, 1.        , 1.        ,
       0.        , 1.        , 0.9859015 , 1.        , 1.     

In [130]:
matrix_item_sin[70].size

249

In [131]:
matrix_item_sin[70].argsort()

array([ 70, 164,  78, 227,  75, 183,  27, 150, 135, 159, 109,  63, 139,
       105, 153,  30, 238,  91,  88,  39,  62, 216, 131, 220, 157, 112,
        48, 106, 125, 178, 225,  82, 177,  81,  67,  23, 145, 103, 170,
       226, 231, 221,  83,  38, 110, 214, 236, 116, 206, 237,  55, 138,
       160,  92,  44, 204, 140,  58,  22, 101, 146, 165, 129, 210, 217,
       130, 223, 149,  79, 136, 224,  43,  85, 115,  16, 143,  60, 243,
       108, 107, 186, 230, 191, 151, 133, 228, 148,  35,  32, 240, 174,
        13,  41, 137, 182,  18, 212, 242, 246, 156,  64, 247,  54, 187,
        46, 114, 121, 211,  50, 207, 222, 162,  33, 188,  24,  20,  10,
       111,  65, 201, 241, 235, 124,  56,   3,  15,  25,   1,   2,   4,
       144, 179, 184, 244,  94,  84,  14, 234, 155, 239,  66,  57,  99,
       176, 197, 195, 189, 126,  96, 193, 202, 113,  76,  40,  72,  19,
       205,  28,  21,  87, 229,  17,  36,  95, 233,  26,  77,  29, 154,
        31, 163,  49, 134, 199, 172, 147,   7,   6,   5,   0,  1

In [132]:
le_country.inverse_transform(matrix_item_sin[70].argsort())

array(['Denmark', 'Norway', 'Estonia', 'Timor-Leste', 'Ecuador', 'Qatar',
       'Bangladesh', 'Montenegro', 'Macedonia (FYROM)', 'New Zealand',
       'Israel', 'Cuba', 'Maldives', 'India', 'Myanmar', 'Belgium',
       'United States', 'Greece', 'Germany', 'Bosnia-Herzegovina',
       'Croatia', 'Sri Lanka', 'Lithuania', 'Sweden', 'Netherlands',
       'Japan', 'Canada', 'Indonesia', 'Latvia', 'Portugal', 'Thailand',
       'Fiji', 'Poland', 'Faroe Islands', 'Czechia', 'Austria',
       'Mediterranean Sea', 'Iceland', 'Panama', 'The Bahamas', 'Turkey',
       'Switzerland', 'Finland', 'Bosnia and Herzegovina', 'Italy',
       'Spain', 'United Arab Emirates', 'Kenya', 'Slovakia',
       'United Kingdom', 'China', 'Malaysia', 'Nicaragua', 'Greenland',
       'Bulgaria', 'Singapore', 'Malta', 'Colombia', 'Australia',
       'Hungary', 'Mexico', 'Oman', 'Libya', 'Somalia', 'Sudan',
       'Liechtenstein', 'Tajikistan', 'Mongolia', 'Ethiopia',
       'Madagascar', 'Tanzania', 'Brunei', 'Fr

In [133]:
le_country.inverse_transform(matrix_item_sin[70].argsort()).size

249